force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <description>Indicates whether the record is currently visible in lookups, indicating a valid selection. Inactive records may still exist and be referenced by existing records, but no new references can be made.</description>
    <inlineHelpText>Indicates whether the record is currently visible in lookups, indicating a valid selection. Inactive records may still exist and be referenced by existing records, but no new references can be made.</inlineHelpText>
    <label>Is Active</label>
    <defaultValue>false</defaultValue>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/IsLimitedService__c.field-meta.xml
<CustomField>
    <fullName>IsLimitedService__c</fullName>
    <description>This flag indicates that the property is Delphi Select.</description>
    <inlineHelpText>This flag indicates that the property is Delphi Select.</inlineHelpText>
    <label>Is Limited Service</label>
    <defaultValue>false</defaultValue>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PropertyMessageCls.cls
public with sharing class PropertyMessageCls {

  public String propertyId{get;set;}
  public Location__c property {get;set;}
  public string propertyInactiveTaxGroupMessage{get;set;}
  public boolean propertyInactiveTaxGroup{get;set;}

  public string propertyIsLimitedServiceMessage{get;set;}
  public boolean propertyIsLimitedService{get;set;}

  public string propertyIsInactiveMessage{get;set;}
  public boolean propertyIsInactive{get;set;}

  public boolean showBlock{get;set;}
  public string defaultMessage {get;set;}

     public PropertyMessageCls(ApexPages.StandardController stdController)
    {
       propertyId = String.escapeSingleQuotes(EncodingUtil.urlEncode(ApexPages.currentPage().getParameters().get('id'), 'UTF-8'));

      Security.checkAreFieldsAccessible('Location__c', new List<String>{'Id', 'IsLimitedService__c', 'IsActive__c'});

    //US 457986 - Replaced Location query with LocationSelector class method
    List<id> listLocationid = new List<id>{propertyId};
    List<Location__c> lstLocation = LocationsSelector.getLocationsById(listLocationid).values();
    if(!lstLocation.IsEmpty()){
      property = lstLocation[0];
    }

        propertyInactiveTaxGroupMessage = '';
        propertyInactiveTaxGroup = false;

        propertyIsLimitedServiceMessage = '';
        propertyIsLimitedService = false;

        propertyIsInactiveMessage = '';
        propertyIsInactive = false;

        showBlock = false;
        CreateMessages();

    defaultMessage = Label.PropertyMessageDefault;
    }

    public void CreateMessages()
    {
      Security.checkAreFieldsAccessible('Location__c', new List<String>{'DefaultTaxGroup__c'});

    boolean isInvalid = TaxGroupCls.isDefaultInactiveForLocation(propertyId);
      if(isInvalid){
      propertyInactiveTaxGroupMessage = Label.PropertyInactiveTaxGroup;
          propertyInactiveTaxGroup = true;
          showBlock = true;
      }

      propertyIsLimitedService = property.IsLimitedService__c;
      if(propertyIsLimitedService) {
        propertyIsLimitedServiceMessage = Label.PropertyIsLimitedService;
        showBlock = true;
      }

      propertyIsInactive = property.IsActive__c;
      if(!propertyIsInactive) {
        propertyIsInactiveMessage = Label.PropertyIsInactive;
        showBlock = true;
      }
    }

}