force-app/main/default/objects/BookingEvent__c/BookingEvent__c.object-meta.xml
<CustomObject>
    <label>Booking Event</label>
    <pluralLabel>Booking Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
</CustomObject>

force-app/main/default/objects/BookingEvent__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipName>Booking_BookingEvent</relationshipName>
    <relationshipLabel>Booking (BookingEvent)</relationshipLabel>
    <type>Lookup</type>
    <deleteConstraint>SetNull</deleteConstraint>
</CustomField>

force-app/main/default/objects/BookingEvent__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BookingEvent__c/fields/EndDateTime__c.field-meta.xml
<CustomField>
    <fullName>EndDateTime__c</fullName>
    <label>End Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BookingEvent__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BookingEvent__c/fields/StartDateTime__c.field-meta.xml
<CustomField>
    <fullName>StartDateTime__c</fullName>
    <label>Start Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/EventItem__c/EventItem__c.object-meta.xml
<CustomObject>
    <label>Event Item</label>
    <pluralLabel>Event Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
</CustomObject>

force-app/main/default/objects/EventItem__c/fields/ActualQuantity__c.field-meta.xml
<CustomField>
    <fullName>ActualQuantity__c</fullName>
    <label>Actual Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EventItem__c/fields/BookedQuantity__c.field-meta.xml
<CustomField>
    <fullName>BookedQuantity__c</fullName>
    <label>Booked Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EventItem__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipName>Booking_EventItem</relationshipName>
    <relationshipLabel>Booking (EventItem)</relationshipLabel>
    <type>Lookup</type>
    <deleteConstraint>SetNull</deleteConstraint>
</CustomField>

force-app/main/default/objects/EventItem__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EventItem__c/fields/DoNotPrintOnBeo__c.field-meta.xml
<CustomField>
    <fullName>DoNotPrintOnBeo__c</fullName>
    <label>Do Not Print On BEO</label>
    <defaultValue>false</defaultValue>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EventItem__c/fields/DoNotPrintOnCheck__c.field-meta.xml
<CustomField>
    <fullName>DoNotPrintOnCheck__c</fullName>
    <label>Do Not Print On Check</label>
    <defaultValue>false</defaultValue>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EventItem__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>BookingEvent__c</referenceTo>
    <relationshipName>Event_EventItem</relationshipName>
    <relationshipLabel>Event (EventItem)</relationshipLabel>
    <type>Lookup</type>
    <deleteConstraint>Restrict</deleteConstraint>
    <required>true</required>
</CustomField>

force-app/main/default/objects/EventItem__c/fields/HidePriceOnBeo__c.field-meta.xml
<CustomField>
    <fullName>HidePriceOnBeo__c</fullName>
    <label>Hide Price On BEO</label>
    <defaultValue>false</defaultValue>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EventItem__c/fields/HideQuantityOnBeo__c.field-meta.xml
<CustomField>
    <fullName>HideQuantityOnBeo__c</fullName>
    <label>Hide Quantity On BEO</label>
    <defaultValue>false</defaultValue>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EventItem__c/fields/InclusiveUnitPrice__c.field-meta.xml
<CustomField>
    <fullName>InclusiveUnitPrice__c</fullName>
    <label>zNI InclusiveUnitPrice</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/EventItem__c/fields/ItemType__c.field-meta.xml
<CustomField>
    <fullName>ItemType__c</fullName>
    <label>Item Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Item</fullName>
            </value>
            <value>
                <fullName>Simple Menu</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Detailed Menu</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EventItem__c/fields/QuantityCalculation__c.field-meta.xml
<CustomField>
    <fullName>QuantityCalculation__c</fullName>
    <label>Quantity Calculation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Calculated</fullName>
            </value>
            <value>
                <fullName>Per Person</fullName>
            </value>
            <value>
                <fullName>Per Event</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EventItem__c/fields/ServiceEndDate__c.field-meta.xml
<CustomField>
    <fullName>ServiceEndDate__c</fullName>
    <label>Service End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EventItem__c/fields/ServiceEndDateTime__c.field-meta.xml
<CustomField>
    <fullName>ServiceEndDateTime__c</fullName>
    <label>Serve End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/EventItem__c/fields/ServiceStartDate__c.field-meta.xml
<CustomField>
    <fullName>ServiceStartDate__c</fullName>
    <label>Service Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EventItem__c/fields/ServiceStartDateTime__c.field-meta.xml
<CustomField>
    <fullName>ServiceStartDateTime__c</fullName>
    <label>Serve Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/EventItem__c/fields/SoldByUnit__c.field-meta.xml
<CustomField>
    <fullName>SoldByUnit__c</fullName>
    <label>Sold By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventItem__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item__c/fields/DoNotPrintOnBeo__c.field-meta.xml
<CustomField>
    <fullName>DoNotPrintOnBeo__c</fullName>
    <description>Don&apos;t print this item on the Banquet Event Order.</description>
    <inlineHelpText>Don&apos;t print this item on the Banquet Event Order.</inlineHelpText>
    <label>Do Not Print On Beo</label>
    <defaultValue>false</defaultValue>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/DoNotPrintOnCheck__c.field-meta.xml
<CustomField>
    <fullName>DoNotPrintOnCheck__c</fullName>
    <description>Don&apos;t print on banquet check.</description>
    <inlineHelpText>Don&apos;t print on banquet check.</inlineHelpText>
    <label>Do Not Print On Check</label>
    <defaultValue>false</defaultValue>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/HidePriceOnBeo__c.field-meta.xml
<CustomField>
    <fullName>HidePriceOnBeo__c</fullName>
    <description>Don&apos;t show the item price on the Banquet Event Order.</description>
    <inlineHelpText>Don&apos;t show the item price on the Banquet Event Order.</inlineHelpText>
    <label>Hide Price On Beo</label>
    <defaultValue>false</defaultValue>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/HideQuantityOnBeo__c.field-meta.xml
<CustomField>
    <fullName>HideQuantityOnBeo__c</fullName>
    <description>Don&apos;t show the item quantity on the Banquet Event Order.</description>
    <inlineHelpText>Don&apos;t show the item quantity on the Banquet Event Order.</inlineHelpText>
    <label>Hide Quantity On Beo</label>
    <defaultValue>false</defaultValue>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/ItemType__c.field-meta.xml
<CustomField>
    <fullName>ItemType__c</fullName>
    <description>Specifies whether this item is a single item, a menu, or a text item for display on a BEO.  VALUE OPTIONS ARE FIXED BY DELPHI.FDC AND SHOULD NOT BE MODIFIED.</description>
    <inlineHelpText>Specifies whether this item is a single item, a menu, or a text item for display on a BEO.  VALUE OPTIONS ARE FIXED BY DELPHI.FDC AND SHOULD NOT BE MODIFIED.</inlineHelpText>
    <label>Item Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Value1</fullName>
                <label>Value 1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Item__c/fields/QuantityCalculation__c.field-meta.xml
<CustomField>
    <fullName>QuantityCalculation__c</fullName>
    <description>If Per Event, then quantities will be calculated as per the whole event, e.g. with a factor of 1. If Per Person, then quantities will be calculated by multiplying by number of attendees. VALUE OPTIONS ARE FIXED BY DELPHI.FDC AND SHOULD NOT BE MODIFIED.</description>
    <inlineHelpText>If Per Event, then quantities will be calculated as per the whole event, e.g. with a factor of 1. If Per Person, then quantities will be calculated by multiplying by number of attendees. VALUE OPTIONS ARE FIXED BY DELPHI.FDC AND SHOULD NOT BE MODIFIED.</inlineHelpText>
    <label>Quantity Calculation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Value1</fullName>
                <label>Value 1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Item__c/fields/SoldByUnit__c.field-meta.xml
<CustomField>
    <fullName>SoldByUnit__c</fullName>
    <description>Unit of measure in which unit prices are expressed.</description>
    <inlineHelpText>Unit of measure in which unit prices are expressed.</inlineHelpText>
    <label>Sold By Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <description>The unit price exclusive of discount, service charges and taxes.</description>
    <inlineHelpText>The unit price exclusive of discount, service charges and taxes.</inlineHelpText>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TaxGroup__c/TaxGroup__c.object-meta.xml
<CustomObject>
    <label>Tax Group</label>
    <nameField>
        <label>Tax Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TaxGroup__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>The latest date for which the Tax Group applies.</description>
    <inlineHelpText>The latest date for which the Tax Group applies.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TaxGroup__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>The earliest date for which the Tax Group applies.</description>
    <inlineHelpText>The earliest date for which the Tax Group applies.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/EventItemsController.cls
/**
 * @description Controller for managing Event Items on Booking Events
 * Handles retrieving catalogue items and creating EventItem__c records
 */
public with sharing class EventItemsController {

    /**
     * @description Get all EventItem__c records for a specific BookingEvent__c
     * @param bookingEventId The ID of the BookingEvent__c record
     * @return List of EventItem__c records with key fields
     */
    @AuraEnabled(cacheable=true)
    public static List<EventItem__c> getEventItems(Id bookingEventId) {
        return [
            SELECT Id, Name, ItemType__c, QuantityCalculation__c,
                   BookedQuantity__c, ActualQuantity__c, UnitPrice__c,
                   InclusiveUnitPrice__c, SoldByUnit__c, Description__c,
                   ServiceStartDate__c, ServiceStartDateTime__c,
                   ServiceEndDate__c, ServiceEndDateTime__c,
                   DoNotPrintOnBeo__c, DoNotPrintOnCheck__c,
                   HidePriceOnBeo__c, HideQuantityOnBeo__c,
                   Booking__c, Event__c
            FROM EventItem__c
            WHERE Event__c = :bookingEventId
            ORDER BY Name ASC
        ];
    }

    /**
     * @description Get BookingEvent__c details including property info
     * @param bookingEventId The ID of the BookingEvent__c record
     * @return BookingEvent__c record with property and booking details
     */
    @AuraEnabled(cacheable=true)
    public static BookingEvent__c getBookingEventDetails(Id bookingEventId) {
        return [
            SELECT Id, Name, Property__c, Booking__c,
                   Booking__r.Name, Booking__r.Property__c,
                   StartDateTime__c, EndDateTime__c
            FROM BookingEvent__c
            WHERE Id = :bookingEventId
            LIMIT 1
        ];
    }

    /**
     * @description Get available catalogue items from the property
     * @param propertyName The property name (picklist value) to filter items
     * @return List of Item__c records available for selection
     */
    @AuraEnabled(cacheable=true)
    public static List<Item__c> getCatalogueItems(String propertyName) {
        // First try to find items by Location name matching the property
        List<Item__c> items = [
            SELECT Id, Name, ItemType__c, QuantityCalculation__c,
                   UnitPrice__c, IsInclusive__c, SoldByUnit__c,
                   ServingUnit__c, Description__c, RichDescription__c,
                   RevenueClassification__c, ItemCategory__c,
                   AdminCharge__c, Gratuity__c, IsActive__c,
                   DoNotPrintOnBeo__c, DoNotPrintOnCheck__c,
                   HidePriceOnBeo__c, HideQuantityOnBeo__c, HideServeTimesOnBeo__c,
                   Property__c, Location__c, Location__r.Name
            FROM Item__c
            WHERE IsActive__c = true
                AND (Location__r.Name = :propertyName
                     OR Property__c = :propertyName)
            ORDER BY ItemType__c, Name ASC
            LIMIT 500
        ];

        // If no items found for the property, return corporate items
        if (items.isEmpty()) {
            items = [
                SELECT Id, Name, ItemType__c, QuantityCalculation__c,
                       UnitPrice__c, IsInclusive__c, SoldByUnit__c,
                       ServingUnit__c, Description__c, RichDescription__c,
                       RevenueClassification__c, ItemCategory__c,
                       AdminCharge__c, Gratuity__c, IsActive__c,
                       DoNotPrintOnBeo__c, DoNotPrintOnCheck__c,
                       HidePriceOnBeo__c, HideQuantityOnBeo__c, HideServeTimesOnBeo__c,
                       Property__c, Location__c, Location__r.Name
                FROM Item__c
                WHERE IsActive__c = true
                    AND Location__c = null
                ORDER BY ItemType__c, Name ASC
                LIMIT 500
            ];
        }

        return items;
    }

    /**
     * @description Create EventItem__c records from selected catalogue items
     * @param bookingEventId The BookingEvent__c to link items to
     * @param bookingId The Booking__c to link items to
     * @param selectedItemIds List of Item__c IDs to create as event items
     * @return Result object with success status and created records
     */
    @AuraEnabled
    public static EventItemCreationResult createEventItems(
        Id bookingEventId,
        Id bookingId,
        List<Id> selectedItemIds
    ) {
        EventItemCreationResult result = new EventItemCreationResult();
        List<EventItem__c> eventItemsToInsert = new List<EventItem__c>();
        List<String> errors = new List<String>();

        Savepoint sp = Database.setSavepoint();

        try {
            // Get the selected catalogue items
            Map<Id, Item__c> catalogueItems = new Map<Id, Item__c>([
                SELECT Id, Name, ItemType__c, QuantityCalculation__c,
                       UnitPrice__c, IsInclusive__c, SoldByUnit__c,
                       ServingUnit__c, Description__c, RichDescription__c,
                       RevenueClassification__c, AdminCharge__c, Gratuity__c,
                       DoNotPrintOnBeo__c, DoNotPrintOnCheck__c,
                       HidePriceOnBeo__c, HideQuantityOnBeo__c, HideServeTimesOnBeo__c,
                       AdminIsIncludedInInclusivePrice__c, GratuityIsIncludedInInclusivePrice__c,
                       AllowDecimalQuantities__c, EstimatedConsumptionPercentage__c
                FROM Item__c
                WHERE Id IN :selectedItemIds
            ]);

            // Get the BookingEvent to inherit dates
            BookingEvent__c bookingEvent = [
                SELECT Id, StartDateTime__c, EndDateTime__c,
                       StartDate__c, EndDate__c
                FROM BookingEvent__c
                WHERE Id = :bookingEventId
                LIMIT 1
            ];

            // Create EventItem__c records
            for (Id itemId : selectedItemIds) {
                Item__c catalogueItem = catalogueItems.get(itemId);
                if (catalogueItem == null) {
                    errors.add('Item not found: ' + itemId);
                    continue;
                }

                EventItem__c eventItem = new EventItem__c();
                eventItem.Name = catalogueItem.Name;
                eventItem.Event__c = bookingEventId;
                eventItem.Booking__c = bookingId;

                // Copy fields from catalogue item
                eventItem.ItemType__c = catalogueItem.ItemType__c;
                eventItem.QuantityCalculation__c = catalogueItem.QuantityCalculation__c;
                eventItem.UnitPrice__c = catalogueItem.UnitPrice__c;
                eventItem.SoldByUnit__c = catalogueItem.SoldByUnit__c;
                eventItem.Description__c = catalogueItem.Description__c;
                eventItem.RichDescription__c = catalogueItem.RichDescription__c;
                eventItem.AdminCharge__c = catalogueItem.AdminCharge__c;
                eventItem.Gratuity__c = catalogueItem.Gratuity__c;
                eventItem.DoNotPrintOnBeo__c = catalogueItem.DoNotPrintOnBeo__c;
                eventItem.DoNotPrintOnCheck__c = catalogueItem.DoNotPrintOnCheck__c;
                eventItem.HidePriceOnBeo__c = catalogueItem.HidePriceOnBeo__c;
                eventItem.HideQuantityOnBeo__c = catalogueItem.HideQuantityOnBeo__c;
                eventItem.HideServeTimesOnBeo__c = catalogueItem.HideServeTimesOnBeo__c;
                eventItem.AdminIsIncludedInInclusivePrice__c = catalogueItem.AdminIsIncludedInInclusivePrice__c;
                eventItem.GratuityIsIncludedInInclusivePrice__c = catalogueItem.GratuityIsIncludedInInclusivePrice__c;
                eventItem.AllowDecimalQuantities__c = catalogueItem.AllowDecimalQuantities__c;
                eventItem.EstimatedConsumptionPercentage__c = catalogueItem.EstimatedConsumptionPercentage__c;

                // Set inclusive price if item is marked as inclusive
                if (catalogueItem.IsInclusive__c == true) {
                    eventItem.InclusiveUnitPrice__c = catalogueItem.UnitPrice__c;
                }

                // Set default quantities
                eventItem.BookedQuantity__c = 1;

                // Set service dates/times from event
                eventItem.ServiceStartDate__c = bookingEvent.StartDate__c;
                eventItem.ServiceEndDate__c = bookingEvent.EndDate__c;
                eventItem.ServiceStartDateTime__c = bookingEvent.StartDateTime__c;
                eventItem.ServiceEndDateTime__c = bookingEvent.EndDateTime__c;

                eventItemsToInsert.add(eventItem);
            }

            // Insert event items
            if (!eventItemsToInsert.isEmpty()) {
                Database.SaveResult[] saveResults = Database.insert(eventItemsToInsert, false);

                Integer successCount = 0;
                Integer failureCount = 0;

                for (Integer i = 0; i < saveResults.size(); i++) {
                    Database.SaveResult sr = saveResults[i];
                    if (sr.isSuccess()) {
                        result.createdItemIds.add(sr.getId());
                        successCount++;
                    } else {
                        failureCount++;
                        String errorMsg = 'Item "' + eventItemsToInsert[i].Name + '" failed: ';
                        for (Database.Error err : sr.getErrors()) {
                            errorMsg += err.getMessage() + '; ';
                        }
                        errors.add(errorMsg);
                    }
                }

                result.successCount = successCount;
                result.failureCount = failureCount;
            }

            if (!errors.isEmpty()) {
                result.errors = errors;
                result.hasErrors = true;
            }

            result.success = !eventItemsToInsert.isEmpty() && result.failureCount == 0;
            result.message = generateResultMessage(result.successCount, result.failureCount);

        } catch (Exception e) {
            Database.rollback(sp);
            result.success = false;
            result.hasErrors = true;
            result.message = 'Failed to create event items: ' + e.getMessage();
            result.errors = new List<String>{ e.getMessage() };
        }

        return result;
    }

    /**
     * @description Delete EventItem__c records
     * @param eventItemIds List of EventItem__c IDs to delete
     * @return Result object with success status
     */
    @AuraEnabled
    public static EventItemCreationResult deleteEventItems(List<Id> eventItemIds) {
        EventItemCreationResult result = new EventItemCreationResult();

        try {
            List<EventItem__c> itemsToDelete = [
                SELECT Id, Name
                FROM EventItem__c
                WHERE Id IN :eventItemIds
            ];

            if (!itemsToDelete.isEmpty()) {
                Database.DeleteResult[] deleteResults = Database.delete(itemsToDelete, false);

                Integer successCount = 0;
                Integer failureCount = 0;
                List<String> errors = new List<String>();

                for (Integer i = 0; i < deleteResults.size(); i++) {
                    if (deleteResults[i].isSuccess()) {
                        successCount++;
                    } else {
                        failureCount++;
                        for (Database.Error err : deleteResults[i].getErrors()) {
                            errors.add('Failed to delete "' + itemsToDelete[i].Name + '": ' + err.getMessage());
                        }
                    }
                }

                result.successCount = successCount;
                result.failureCount = failureCount;
                result.success = failureCount == 0;
                result.message = successCount + ' item(s) deleted successfully';

                if (!errors.isEmpty()) {
                    result.errors = errors;
                    result.hasErrors = true;
                }
            }
        } catch (Exception e) {
            result.success = false;
            result.hasErrors = true;
            result.message = 'Failed to delete items: ' + e.getMessage();
            result.errors = new List<String>{ e.getMessage() };
        }

        return result;
    }

    /**
     * @description Update EventItem__c records
     * @param eventItemsJson JSON string of event items to update
     * @return Result object with success status
     */
    @AuraEnabled
    public static EventItemCreationResult updateEventItems(String eventItemsJson) {
        EventItemCreationResult result = new EventItemCreationResult();

        try {
            List<Map<String, Object>> itemUpdates = (List<Map<String, Object>>)
                JSON.deserializeUntyped(eventItemsJson);

            List<EventItem__c> itemsToUpdate = new List<EventItem__c>();

            for (Map<String, Object> itemData : itemUpdates) {
                EventItem__c item = new EventItem__c();
                item.Id = (Id) itemData.get('Id');

                if (itemData.containsKey('BookedQuantity__c')) {
                    item.BookedQuantity__c = (Decimal) itemData.get('BookedQuantity__c');
                }
                if (itemData.containsKey('ActualQuantity__c')) {
                    item.ActualQuantity__c = (Decimal) itemData.get('ActualQuantity__c');
                }
                if (itemData.containsKey('UnitPrice__c')) {
                    item.UnitPrice__c = (Decimal) itemData.get('UnitPrice__c');
                }

                itemsToUpdate.add(item);
            }

            if (!itemsToUpdate.isEmpty()) {
                Database.SaveResult[] saveResults = Database.update(itemsToUpdate, false);

                Integer successCount = 0;
                Integer failureCount = 0;
                List<String> errors = new List<String>();

                for (Integer i = 0; i < saveResults.size(); i++) {
                    if (saveResults[i].isSuccess()) {
                        successCount++;
                    } else {
                        failureCount++;
                        for (Database.Error err : saveResults[i].getErrors()) {
                            errors.add(err.getMessage());
                        }
                    }
                }

                result.successCount = successCount;
                result.failureCount = failureCount;
                result.success = failureCount == 0;
                result.message = successCount + ' item(s) updated successfully';

                if (!errors.isEmpty()) {
                    result.errors = errors;
                    result.hasErrors = true;
                }
            }
        } catch (Exception e) {
            result.success = false;
            result.hasErrors = true;
            result.message = 'Failed to update items: ' + e.getMessage();
            result.errors = new List<String>{ e.getMessage() };
        }

        return result;
    }

    /**
     * @description Generate result message
     */
    private static String generateResultMessage(Integer successCount, Integer failureCount) {
        if (successCount > 0 && failureCount == 0) {
            return 'Successfully added ' + successCount + ' item' + (successCount > 1 ? 's' : '');
        } else if (successCount > 0 && failureCount > 0) {
            return 'Added ' + successCount + ' item' + (successCount > 1 ? 's' : '') +
                   ', ' + failureCount + ' failed';
        } else if (failureCount > 0) {
            return 'Failed to add ' + failureCount + ' item' + (failureCount > 1 ? 's' : '');
        } else {
            return 'No items were added';
        }
    }

    /**
     * @description Result wrapper class
     */
    public class EventItemCreationResult {
        @AuraEnabled public Boolean success;
        @AuraEnabled public String message;
        @AuraEnabled public List<Id> createdItemIds;
        @AuraEnabled public Integer successCount;
        @AuraEnabled public Integer failureCount;
        @AuraEnabled public Boolean hasErrors;
        @AuraEnabled public List<String> errors;

        public EventItemCreationResult() {
            this.success = false;
            this.createdItemIds = new List<Id>();
            this.errors = new List<String>();
            this.successCount = 0;
            this.failureCount = 0;
            this.hasErrors = false;
        }
    }
}